bucket_id = 'datapipline'
file_name = 'Planner_Search_Political Events.xlsx'
project_id = 'flawless-will-388608'
table_id = 'bio'
dataset_id = 'etl'
sender_email = "sainidamann@gmail.com"
sender_password = "kpwvdsxqtcaxbdil"
receiver_email = "naveen_nidamanuri@persistent.com"
subject = "Notification"
sm_server = "smtp.gmail.com"
port = 587
json = 'flawless-will-388608-87fa3f5c1357.json'
output_bucket = 'etloutput'
etl_tracker = 'etl_tracker'
progress = 'Inprogress'
success = 'success'
failed = 'failed'
mandatory_column = 'Id'
